// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/v1/collection.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectionConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ArenaSizeBytes uint64                 `protobuf:"varint,1,opt,name=arena_size_bytes,json=arenaSizeBytes,proto3" json:"arena_size_bytes,omitempty"`
	VecDim         int32                  `protobuf:"varint,2,opt,name=vec_dim,json=vecDim,proto3" json:"vec_dim,omitempty"`
	CentroidRate   int32                  `protobuf:"varint,3,opt,name=centroid_rate,json=centroidRate,proto3" json:"centroid_rate,omitempty"`
	SyncSchedule   string                 `protobuf:"bytes,4,opt,name=sync_schedule,json=syncSchedule,proto3" json:"sync_schedule,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionConfig) Reset() {
	*x = CollectionConfig{}
	mi := &file_proto_v1_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionConfig) ProtoMessage() {}

func (x *CollectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionConfig.ProtoReflect.Descriptor instead.
func (*CollectionConfig) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionConfig) GetArenaSizeBytes() uint64 {
	if x != nil {
		return x.ArenaSizeBytes
	}
	return 0
}

func (x *CollectionConfig) GetVecDim() int32 {
	if x != nil {
		return x.VecDim
	}
	return 0
}

func (x *CollectionConfig) GetCentroidRate() int32 {
	if x != nil {
		return x.CentroidRate
	}
	return 0
}

func (x *CollectionConfig) GetSyncSchedule() string {
	if x != nil {
		return x.SyncSchedule
	}
	return ""
}

type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Config        *CollectionConfig      `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Connectors    []string               `protobuf:"bytes,9,rep,name=connectors,proto3" json:"connectors,omitempty"`
	ShardIds      []uint32               `protobuf:"varint,10,rep,packed,name=shard_ids,json=shardIds,proto3" json:"shard_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_proto_v1_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{1}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Collection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Collection) GetConfig() *CollectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Collection) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Collection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Collection) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Collection) GetConnectors() []string {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *Collection) GetShardIds() []uint32 {
	if x != nil {
		return x.ShardIds
	}
	return nil
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Config        *CollectionConfig      `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_proto_v1_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCollectionRequest) GetConfig() *CollectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_proto_v1_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{3}
}

func (x *GetCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_proto_v1_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{4}
}

func (x *ListCollectionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_proto_v1_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

type UpdateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionRequest) Reset() {
	*x = UpdateCollectionRequest{}
	mi := &file_proto_v1_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionRequest) ProtoMessage() {}

func (x *UpdateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_proto_v1_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_proto_v1_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCollectionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionResponse) Reset() {
	*x = CollectionResponse{}
	mi := &file_proto_v1_collection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionResponse) ProtoMessage() {}

func (x *CollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionResponse.ProtoReflect.Descriptor instead.
func (*CollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{9}
}

func (x *CollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type CollectionSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionIds []string               `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"` // empty = all collections
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	QueryVector   []float32              `protobuf:"fixed32,3,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TopK          int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionSearchRequest) Reset() {
	*x = CollectionSearchRequest{}
	mi := &file_proto_v1_collection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionSearchRequest) ProtoMessage() {}

func (x *CollectionSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionSearchRequest.ProtoReflect.Descriptor instead.
func (*CollectionSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{10}
}

func (x *CollectionSearchRequest) GetCollectionIds() []string {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

func (x *CollectionSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CollectionSearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *CollectionSearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CollectionSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type CollectionSearchResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*CollectionScoredResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionSearchResponse) Reset() {
	*x = CollectionSearchResponse{}
	mi := &file_proto_v1_collection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionSearchResponse) ProtoMessage() {}

func (x *CollectionSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionSearchResponse.ProtoReflect.Descriptor instead.
func (*CollectionSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{11}
}

func (x *CollectionSearchResponse) GetResults() []*CollectionScoredResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type CollectionScoredResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FusedScore    float64                `protobuf:"fixed64,2,opt,name=fused_score,json=fusedScore,proto3" json:"fused_score,omitempty"`
	Bm25Score     float64                `protobuf:"fixed64,3,opt,name=bm25_score,json=bm25Score,proto3" json:"bm25_score,omitempty"`
	SemanticScore float32                `protobuf:"fixed32,4,opt,name=semantic_score,json=semanticScore,proto3" json:"semantic_score,omitempty"`
	CollectionId  string                 `protobuf:"bytes,5,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionScoredResult) Reset() {
	*x = CollectionScoredResult{}
	mi := &file_proto_v1_collection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionScoredResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionScoredResult) ProtoMessage() {}

func (x *CollectionScoredResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_collection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionScoredResult.ProtoReflect.Descriptor instead.
func (*CollectionScoredResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_collection_proto_rawDescGZIP(), []int{12}
}

func (x *CollectionScoredResult) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CollectionScoredResult) GetFusedScore() float64 {
	if x != nil {
		return x.FusedScore
	}
	return 0
}

func (x *CollectionScoredResult) GetBm25Score() float64 {
	if x != nil {
		return x.Bm25Score
	}
	return 0
}

func (x *CollectionScoredResult) GetSemanticScore() float32 {
	if x != nil {
		return x.SemanticScore
	}
	return 0
}

func (x *CollectionScoredResult) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

var File_proto_v1_collection_proto protoreflect.FileDescriptor

const file_proto_v1_collection_proto_rawDesc = "" +
	"\n" +
	"\x19proto/v1/collection.proto\x12\x11yase.ingestion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\x10CollectionConfig\x12(\n" +
	"\x10arena_size_bytes\x18\x01 \x01(\x04R\x0earenaSizeBytes\x12\x17\n" +
	"\avec_dim\x18\x02 \x01(\x05R\x06vecDim\x12#\n" +
	"\rcentroid_rate\x18\x03 \x01(\x05R\fcentroidRate\x12#\n" +
	"\rsync_schedule\x18\x04 \x01(\tR\fsyncSchedule\"\xf7\x02\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\x06config\x18\x05 \x01(\v2#.yase.ingestion.v1.CollectionConfigR\x06config\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1e\n" +
	"\n" +
	"connectors\x18\t \x03(\tR\n" +
	"connectors\x12\x1b\n" +
	"\tshard_ids\x18\n" +
	" \x03(\rR\bshardIds\"\xb9\x01\n" +
	"\x17CreateCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\x06config\x18\x05 \x01(\v2#.yase.ingestion.v1.CollectionConfigR\x06config\"&\n" +
	"\x14GetCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x16ListCollectionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"Z\n" +
	"\x17ListCollectionsResponse\x12?\n" +
	"\vcollections\x18\x01 \x03(\v2\x1d.yase.ingestion.v1.CollectionR\vcollections\"_\n" +
	"\x17UpdateCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\")\n" +
	"\x17DeleteCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18DeleteCollectionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"S\n" +
	"\x12CollectionResponse\x12=\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x1d.yase.ingestion.v1.CollectionR\n" +
	"collection\"\x9d\x02\n" +
	"\x17CollectionSearchRequest\x12%\n" +
	"\x0ecollection_ids\x18\x01 \x03(\tR\rcollectionIds\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12!\n" +
	"\fquery_vector\x18\x03 \x03(\x02R\vqueryVector\x12Q\n" +
	"\afilters\x18\x04 \x03(\v27.yase.ingestion.v1.CollectionSearchRequest.FiltersEntryR\afilters\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x18CollectionSearchResponse\x12C\n" +
	"\aresults\x18\x01 \x03(\v2).yase.ingestion.v1.CollectionScoredResultR\aresults\"\xb4\x01\n" +
	"\x16CollectionScoredResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vfused_score\x18\x02 \x01(\x01R\n" +
	"fusedScore\x12\x1d\n" +
	"\n" +
	"bm25_score\x18\x03 \x01(\x01R\tbm25Score\x12%\n" +
	"\x0esemantic_score\x18\x04 \x01(\x02R\rsemanticScore\x12#\n" +
	"\rcollection_id\x18\x05 \x01(\tR\fcollectionId2\x86\x05\n" +
	"\x11CollectionService\x12e\n" +
	"\x10CreateCollection\x12*.yase.ingestion.v1.CreateCollectionRequest\x1a%.yase.ingestion.v1.CollectionResponse\x12_\n" +
	"\rGetCollection\x12'.yase.ingestion.v1.GetCollectionRequest\x1a%.yase.ingestion.v1.CollectionResponse\x12h\n" +
	"\x0fListCollections\x12).yase.ingestion.v1.ListCollectionsRequest\x1a*.yase.ingestion.v1.ListCollectionsResponse\x12e\n" +
	"\x10UpdateCollection\x12*.yase.ingestion.v1.UpdateCollectionRequest\x1a%.yase.ingestion.v1.CollectionResponse\x12k\n" +
	"\x10DeleteCollection\x12*.yase.ingestion.v1.DeleteCollectionRequest\x1a+.yase.ingestion.v1.DeleteCollectionResponse\x12k\n" +
	"\x10SearchCollection\x12*.yase.ingestion.v1.CollectionSearchRequest\x1a+.yase.ingestion.v1.CollectionSearchResponseB.Z,github.com/efathom/yase/proto/v1;ingestionv1b\x06proto3"

var (
	file_proto_v1_collection_proto_rawDescOnce sync.Once
	file_proto_v1_collection_proto_rawDescData []byte
)

func file_proto_v1_collection_proto_rawDescGZIP() []byte {
	file_proto_v1_collection_proto_rawDescOnce.Do(func() {
		file_proto_v1_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_collection_proto_rawDesc), len(file_proto_v1_collection_proto_rawDesc)))
	})
	return file_proto_v1_collection_proto_rawDescData
}

var file_proto_v1_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_v1_collection_proto_goTypes = []any{
	(*CollectionConfig)(nil),         // 0: yase.ingestion.v1.CollectionConfig
	(*Collection)(nil),               // 1: yase.ingestion.v1.Collection
	(*CreateCollectionRequest)(nil),  // 2: yase.ingestion.v1.CreateCollectionRequest
	(*GetCollectionRequest)(nil),     // 3: yase.ingestion.v1.GetCollectionRequest
	(*ListCollectionsRequest)(nil),   // 4: yase.ingestion.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),  // 5: yase.ingestion.v1.ListCollectionsResponse
	(*UpdateCollectionRequest)(nil),  // 6: yase.ingestion.v1.UpdateCollectionRequest
	(*DeleteCollectionRequest)(nil),  // 7: yase.ingestion.v1.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil), // 8: yase.ingestion.v1.DeleteCollectionResponse
	(*CollectionResponse)(nil),       // 9: yase.ingestion.v1.CollectionResponse
	(*CollectionSearchRequest)(nil),  // 10: yase.ingestion.v1.CollectionSearchRequest
	(*CollectionSearchResponse)(nil), // 11: yase.ingestion.v1.CollectionSearchResponse
	(*CollectionScoredResult)(nil),   // 12: yase.ingestion.v1.CollectionScoredResult
	nil,                              // 13: yase.ingestion.v1.CollectionSearchRequest.FiltersEntry
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_proto_v1_collection_proto_depIdxs = []int32{
	0,  // 0: yase.ingestion.v1.Collection.config:type_name -> yase.ingestion.v1.CollectionConfig
	14, // 1: yase.ingestion.v1.Collection.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: yase.ingestion.v1.Collection.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: yase.ingestion.v1.CreateCollectionRequest.config:type_name -> yase.ingestion.v1.CollectionConfig
	1,  // 4: yase.ingestion.v1.ListCollectionsResponse.collections:type_name -> yase.ingestion.v1.Collection
	1,  // 5: yase.ingestion.v1.CollectionResponse.collection:type_name -> yase.ingestion.v1.Collection
	13, // 6: yase.ingestion.v1.CollectionSearchRequest.filters:type_name -> yase.ingestion.v1.CollectionSearchRequest.FiltersEntry
	12, // 7: yase.ingestion.v1.CollectionSearchResponse.results:type_name -> yase.ingestion.v1.CollectionScoredResult
	2,  // 8: yase.ingestion.v1.CollectionService.CreateCollection:input_type -> yase.ingestion.v1.CreateCollectionRequest
	3,  // 9: yase.ingestion.v1.CollectionService.GetCollection:input_type -> yase.ingestion.v1.GetCollectionRequest
	4,  // 10: yase.ingestion.v1.CollectionService.ListCollections:input_type -> yase.ingestion.v1.ListCollectionsRequest
	6,  // 11: yase.ingestion.v1.CollectionService.UpdateCollection:input_type -> yase.ingestion.v1.UpdateCollectionRequest
	7,  // 12: yase.ingestion.v1.CollectionService.DeleteCollection:input_type -> yase.ingestion.v1.DeleteCollectionRequest
	10, // 13: yase.ingestion.v1.CollectionService.SearchCollection:input_type -> yase.ingestion.v1.CollectionSearchRequest
	9,  // 14: yase.ingestion.v1.CollectionService.CreateCollection:output_type -> yase.ingestion.v1.CollectionResponse
	9,  // 15: yase.ingestion.v1.CollectionService.GetCollection:output_type -> yase.ingestion.v1.CollectionResponse
	5,  // 16: yase.ingestion.v1.CollectionService.ListCollections:output_type -> yase.ingestion.v1.ListCollectionsResponse
	9,  // 17: yase.ingestion.v1.CollectionService.UpdateCollection:output_type -> yase.ingestion.v1.CollectionResponse
	8,  // 18: yase.ingestion.v1.CollectionService.DeleteCollection:output_type -> yase.ingestion.v1.DeleteCollectionResponse
	11, // 19: yase.ingestion.v1.CollectionService.SearchCollection:output_type -> yase.ingestion.v1.CollectionSearchResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_v1_collection_proto_init() }
func file_proto_v1_collection_proto_init() {
	if File_proto_v1_collection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_collection_proto_rawDesc), len(file_proto_v1_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_collection_proto_goTypes,
		DependencyIndexes: file_proto_v1_collection_proto_depIdxs,
		MessageInfos:      file_proto_v1_collection_proto_msgTypes,
	}.Build()
	File_proto_v1_collection_proto = out.File
	file_proto_v1_collection_proto_goTypes = nil
	file_proto_v1_collection_proto_depIdxs = nil
}
