// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/v1/index.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint32                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CollectionId  string                 `protobuf:"bytes,5,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // target collection (empty = _default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_proto_v1_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetDocId() uint32 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *IngestRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IngestRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *IngestRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IngestRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_v1_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	QueryVector   []float32              `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	CollectionId  string                 `protobuf:"bytes,5,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // target collection (empty = _default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_v1_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

type ScoredResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FusedScore    float64                `protobuf:"fixed64,2,opt,name=fused_score,json=fusedScore,proto3" json:"fused_score,omitempty"`
	Bm25Score     float64                `protobuf:"fixed64,3,opt,name=bm25_score,json=bm25Score,proto3" json:"bm25_score,omitempty"`
	SemanticScore float32                `protobuf:"fixed32,4,opt,name=semantic_score,json=semanticScore,proto3" json:"semantic_score,omitempty"`
	CollectionId  string                 `protobuf:"bytes,5,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // which collection this result came from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredResult) Reset() {
	*x = ScoredResult{}
	mi := &file_proto_v1_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredResult) ProtoMessage() {}

func (x *ScoredResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredResult.ProtoReflect.Descriptor instead.
func (*ScoredResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{3}
}

func (x *ScoredResult) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScoredResult) GetFusedScore() float64 {
	if x != nil {
		return x.FusedScore
	}
	return 0
}

func (x *ScoredResult) GetBm25Score() float64 {
	if x != nil {
		return x.Bm25Score
	}
	return 0
}

func (x *ScoredResult) GetSemanticScore() float32 {
	if x != nil {
		return x.SemanticScore
	}
	return 0
}

func (x *ScoredResult) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoredResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_v1_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetResults() []*ScoredResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_v1_index_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{5}
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HnswNodes      int64                  `protobuf:"varint,1,opt,name=hnsw_nodes,json=hnswNodes,proto3" json:"hnsw_nodes,omitempty"`
	ArenaUsedBytes int64                  `protobuf:"varint,2,opt,name=arena_used_bytes,json=arenaUsedBytes,proto3" json:"arena_used_bytes,omitempty"`
	Centroids      int64                  `protobuf:"varint,3,opt,name=centroids,proto3" json:"centroids,omitempty"`
	Leaves         int64                  `protobuf:"varint,4,opt,name=leaves,proto3" json:"leaves,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_v1_index_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{6}
}

func (x *StatsResponse) GetHnswNodes() int64 {
	if x != nil {
		return x.HnswNodes
	}
	return 0
}

func (x *StatsResponse) GetArenaUsedBytes() int64 {
	if x != nil {
		return x.ArenaUsedBytes
	}
	return 0
}

func (x *StatsResponse) GetCentroids() int64 {
	if x != nil {
		return x.Centroids
	}
	return 0
}

func (x *StatsResponse) GetLeaves() int64 {
	if x != nil {
		return x.Leaves
	}
	return 0
}

type ShardSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	QueryVector   []float32              `protobuf:"fixed32,3,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TopK          int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	CollectionId  string                 `protobuf:"bytes,6,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // target collection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardSearchRequest) Reset() {
	*x = ShardSearchRequest{}
	mi := &file_proto_v1_index_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardSearchRequest) ProtoMessage() {}

func (x *ShardSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardSearchRequest.ProtoReflect.Descriptor instead.
func (*ShardSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{7}
}

func (x *ShardSearchRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ShardSearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *ShardSearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ShardSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ShardSearchRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

type ShardSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoredResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ShardId       uint32                 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardSearchResponse) Reset() {
	*x = ShardSearchResponse{}
	mi := &file_proto_v1_index_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardSearchResponse) ProtoMessage() {}

func (x *ShardSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_index_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardSearchResponse.ProtoReflect.Descriptor instead.
func (*ShardSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_index_proto_rawDescGZIP(), []int{8}
}

func (x *ShardSearchResponse) GetResults() []*ScoredResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ShardSearchResponse) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

var File_proto_v1_index_proto protoreflect.FileDescriptor

const file_proto_v1_index_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/index.proto\x12\x11yase.ingestion.v1\"\x80\x02\n" +
	"\rIngestRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\rR\x05docId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..yase.ingestion.v1.IngestRequest.MetadataEntryR\bmetadata\x12#\n" +
	"\rcollection_id\x18\x05 \x01(\tR\fcollectionId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eIngestResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x87\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x02R\vqueryVector\x12G\n" +
	"\afilters\x18\x03 \x03(\v2-.yase.ingestion.v1.SearchRequest.FiltersEntryR\afilters\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x12#\n" +
	"\rcollection_id\x18\x05 \x01(\tR\fcollectionId\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\fScoredResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vfused_score\x18\x02 \x01(\x01R\n" +
	"fusedScore\x12\x1d\n" +
	"\n" +
	"bm25_score\x18\x03 \x01(\x01R\tbm25Score\x12%\n" +
	"\x0esemantic_score\x18\x04 \x01(\x02R\rsemanticScore\x12#\n" +
	"\rcollection_id\x18\x05 \x01(\tR\fcollectionId\"K\n" +
	"\x0eSearchResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.yase.ingestion.v1.ScoredResultR\aresults\"\x0e\n" +
	"\fStatsRequest\"\x8e\x01\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"hnsw_nodes\x18\x01 \x01(\x03R\thnswNodes\x12(\n" +
	"\x10arena_used_bytes\x18\x02 \x01(\x03R\x0earenaUsedBytes\x12\x1c\n" +
	"\tcentroids\x18\x03 \x01(\x03R\tcentroids\x12\x16\n" +
	"\x06leaves\x18\x04 \x01(\x03R\x06leaves\"\xac\x02\n" +
	"\x12ShardSearchRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12!\n" +
	"\fquery_vector\x18\x03 \x03(\x02R\vqueryVector\x12L\n" +
	"\afilters\x18\x04 \x03(\v22.yase.ingestion.v1.ShardSearchRequest.FiltersEntryR\afilters\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x12#\n" +
	"\rcollection_id\x18\x06 \x01(\tR\fcollectionId\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x13ShardSearchResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.yase.ingestion.v1.ScoredResultR\aresults\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\rR\ashardId2\xf8\x01\n" +
	"\fIndexService\x12M\n" +
	"\x06Ingest\x12 .yase.ingestion.v1.IngestRequest\x1a!.yase.ingestion.v1.IngestResponse\x12M\n" +
	"\x06Search\x12 .yase.ingestion.v1.SearchRequest\x1a!.yase.ingestion.v1.SearchResponse\x12J\n" +
	"\x05Stats\x12\x1f.yase.ingestion.v1.StatsRequest\x1a .yase.ingestion.v1.StatsResponse2r\n" +
	"\x12ShardSearchService\x12\\\n" +
	"\vSearchShard\x12%.yase.ingestion.v1.ShardSearchRequest\x1a&.yase.ingestion.v1.ShardSearchResponseB.Z,github.com/efathom/yase/proto/v1;ingestionv1b\x06proto3"

var (
	file_proto_v1_index_proto_rawDescOnce sync.Once
	file_proto_v1_index_proto_rawDescData []byte
)

func file_proto_v1_index_proto_rawDescGZIP() []byte {
	file_proto_v1_index_proto_rawDescOnce.Do(func() {
		file_proto_v1_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_index_proto_rawDesc), len(file_proto_v1_index_proto_rawDesc)))
	})
	return file_proto_v1_index_proto_rawDescData
}

var file_proto_v1_index_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_v1_index_proto_goTypes = []any{
	(*IngestRequest)(nil),       // 0: yase.ingestion.v1.IngestRequest
	(*IngestResponse)(nil),      // 1: yase.ingestion.v1.IngestResponse
	(*SearchRequest)(nil),       // 2: yase.ingestion.v1.SearchRequest
	(*ScoredResult)(nil),        // 3: yase.ingestion.v1.ScoredResult
	(*SearchResponse)(nil),      // 4: yase.ingestion.v1.SearchResponse
	(*StatsRequest)(nil),        // 5: yase.ingestion.v1.StatsRequest
	(*StatsResponse)(nil),       // 6: yase.ingestion.v1.StatsResponse
	(*ShardSearchRequest)(nil),  // 7: yase.ingestion.v1.ShardSearchRequest
	(*ShardSearchResponse)(nil), // 8: yase.ingestion.v1.ShardSearchResponse
	nil,                         // 9: yase.ingestion.v1.IngestRequest.MetadataEntry
	nil,                         // 10: yase.ingestion.v1.SearchRequest.FiltersEntry
	nil,                         // 11: yase.ingestion.v1.ShardSearchRequest.FiltersEntry
}
var file_proto_v1_index_proto_depIdxs = []int32{
	9,  // 0: yase.ingestion.v1.IngestRequest.metadata:type_name -> yase.ingestion.v1.IngestRequest.MetadataEntry
	10, // 1: yase.ingestion.v1.SearchRequest.filters:type_name -> yase.ingestion.v1.SearchRequest.FiltersEntry
	3,  // 2: yase.ingestion.v1.SearchResponse.results:type_name -> yase.ingestion.v1.ScoredResult
	11, // 3: yase.ingestion.v1.ShardSearchRequest.filters:type_name -> yase.ingestion.v1.ShardSearchRequest.FiltersEntry
	3,  // 4: yase.ingestion.v1.ShardSearchResponse.results:type_name -> yase.ingestion.v1.ScoredResult
	0,  // 5: yase.ingestion.v1.IndexService.Ingest:input_type -> yase.ingestion.v1.IngestRequest
	2,  // 6: yase.ingestion.v1.IndexService.Search:input_type -> yase.ingestion.v1.SearchRequest
	5,  // 7: yase.ingestion.v1.IndexService.Stats:input_type -> yase.ingestion.v1.StatsRequest
	7,  // 8: yase.ingestion.v1.ShardSearchService.SearchShard:input_type -> yase.ingestion.v1.ShardSearchRequest
	1,  // 9: yase.ingestion.v1.IndexService.Ingest:output_type -> yase.ingestion.v1.IngestResponse
	4,  // 10: yase.ingestion.v1.IndexService.Search:output_type -> yase.ingestion.v1.SearchResponse
	6,  // 11: yase.ingestion.v1.IndexService.Stats:output_type -> yase.ingestion.v1.StatsResponse
	8,  // 12: yase.ingestion.v1.ShardSearchService.SearchShard:output_type -> yase.ingestion.v1.ShardSearchResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_v1_index_proto_init() }
func file_proto_v1_index_proto_init() {
	if File_proto_v1_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_index_proto_rawDesc), len(file_proto_v1_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_v1_index_proto_goTypes,
		DependencyIndexes: file_proto_v1_index_proto_depIdxs,
		MessageInfos:      file_proto_v1_index_proto_msgTypes,
	}.Build()
	File_proto_v1_index_proto = out.File
	file_proto_v1_index_proto_goTypes = nil
	file_proto_v1_index_proto_depIdxs = nil
}
