// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.2
// source: proto/v1/ingestion.proto

package ingestionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestionService_IngestBatch_FullMethodName  = "/yase.ingestion.v1.IngestionService/IngestBatch"
	IngestionService_IngestStream_FullMethodName = "/yase.ingestion.v1.IngestionService/IngestStream"
)

// IngestionServiceClient is the client API for IngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IngestionService provides both batch and streaming ingestion endpoints.
type IngestionServiceClient interface {
	// IngestBatch processes bulk, latency-tolerant historical data.
	IngestBatch(ctx context.Context, in *BatchIngestRequest, opts ...grpc.CallOption) (*BatchIngestResponse, error)
	// IngestStream handles sub-second, real-time bidirectional streaming
	// from crawler nodes.
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamIngestRequest, StreamIngestResponse], error)
}

type ingestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionServiceClient(cc grpc.ClientConnInterface) IngestionServiceClient {
	return &ingestionServiceClient{cc}
}

func (c *ingestionServiceClient) IngestBatch(ctx context.Context, in *BatchIngestRequest, opts ...grpc.CallOption) (*BatchIngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchIngestResponse)
	err := c.cc.Invoke(ctx, IngestionService_IngestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionServiceClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamIngestRequest, StreamIngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionService_ServiceDesc.Streams[0], IngestionService_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamIngestRequest, StreamIngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionService_IngestStreamClient = grpc.BidiStreamingClient[StreamIngestRequest, StreamIngestResponse]

// IngestionServiceServer is the server API for IngestionService service.
// All implementations must embed UnimplementedIngestionServiceServer
// for forward compatibility.
//
// IngestionService provides both batch and streaming ingestion endpoints.
type IngestionServiceServer interface {
	// IngestBatch processes bulk, latency-tolerant historical data.
	IngestBatch(context.Context, *BatchIngestRequest) (*BatchIngestResponse, error)
	// IngestStream handles sub-second, real-time bidirectional streaming
	// from crawler nodes.
	IngestStream(grpc.BidiStreamingServer[StreamIngestRequest, StreamIngestResponse]) error
	mustEmbedUnimplementedIngestionServiceServer()
}

// UnimplementedIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionServiceServer struct{}

func (UnimplementedIngestionServiceServer) IngestBatch(context.Context, *BatchIngestRequest) (*BatchIngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestBatch not implemented")
}
func (UnimplementedIngestionServiceServer) IngestStream(grpc.BidiStreamingServer[StreamIngestRequest, StreamIngestResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedIngestionServiceServer) mustEmbedUnimplementedIngestionServiceServer() {}
func (UnimplementedIngestionServiceServer) testEmbeddedByValue()                          {}

// UnsafeIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionServiceServer will
// result in compilation errors.
type UnsafeIngestionServiceServer interface {
	mustEmbedUnimplementedIngestionServiceServer()
}

func RegisterIngestionServiceServer(s grpc.ServiceRegistrar, srv IngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionService_ServiceDesc, srv)
}

func _IngestionService_IngestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionServiceServer).IngestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionService_IngestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionServiceServer).IngestBatch(ctx, req.(*BatchIngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionService_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestionServiceServer).IngestStream(&grpc.GenericServerStream[StreamIngestRequest, StreamIngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionService_IngestStreamServer = grpc.BidiStreamingServer[StreamIngestRequest, StreamIngestResponse]

// IngestionService_ServiceDesc is the grpc.ServiceDesc for IngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yase.ingestion.v1.IngestionService",
	HandlerType: (*IngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestBatch",
			Handler:    _IngestionService_IngestBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _IngestionService_IngestStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v1/ingestion.proto",
}
