// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/v1/ingestion.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CrawlRecord represents a single crawled document.
// Uses bytes for raw_content instead of string to skip Go runtime UTF-8 validation
// during unmarshaling, reducing allocation overhead.
type CrawlRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	RawContent    []byte                 `protobuf:"bytes,2,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CrawledAtUnix int64                  `protobuf:"varint,4,opt,name=crawled_at_unix,json=crawledAtUnix,proto3" json:"crawled_at_unix,omitempty"`
	CollectionId  string                 `protobuf:"bytes,5,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // target collection (empty = _default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlRecord) Reset() {
	*x = CrawlRecord{}
	mi := &file_proto_v1_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlRecord) ProtoMessage() {}

func (x *CrawlRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlRecord.ProtoReflect.Descriptor instead.
func (*CrawlRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlRecord) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CrawlRecord) GetRawContent() []byte {
	if x != nil {
		return x.RawContent
	}
	return nil
}

func (x *CrawlRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CrawlRecord) GetCrawledAtUnix() int64 {
	if x != nil {
		return x.CrawledAtUnix
	}
	return 0
}

func (x *CrawlRecord) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

// BatchIngestRequest batches multiple records to reduce HTTP/2 framing overhead.
type BatchIngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*CrawlRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIngestRequest) Reset() {
	*x = BatchIngestRequest{}
	mi := &file_proto_v1_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIngestRequest) ProtoMessage() {}

func (x *BatchIngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIngestRequest.ProtoReflect.Descriptor instead.
func (*BatchIngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *BatchIngestRequest) GetRecords() []*CrawlRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type BatchIngestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedCount int32                  `protobuf:"varint,1,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchIngestResponse) Reset() {
	*x = BatchIngestResponse{}
	mi := &file_proto_v1_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIngestResponse) ProtoMessage() {}

func (x *BatchIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIngestResponse.ProtoReflect.Descriptor instead.
func (*BatchIngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *BatchIngestResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *BatchIngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// StreamIngestRequest wraps a single record for bidirectional streaming.
type StreamIngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *CrawlRecord           `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIngestRequest) Reset() {
	*x = StreamIngestRequest{}
	mi := &file_proto_v1_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIngestRequest) ProtoMessage() {}

func (x *StreamIngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIngestRequest.ProtoReflect.Descriptor instead.
func (*StreamIngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *StreamIngestRequest) GetRecord() *CrawlRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type StreamIngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIngestResponse) Reset() {
	*x = StreamIngestResponse{}
	mi := &file_proto_v1_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIngestResponse) ProtoMessage() {}

func (x *StreamIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIngestResponse.ProtoReflect.Descriptor instead.
func (*StreamIngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingestion_proto_rawDescGZIP(), []int{4}
}

func (x *StreamIngestResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StreamIngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_v1_ingestion_proto protoreflect.FileDescriptor

const file_proto_v1_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/ingestion.proto\x12\x11yase.ingestion.v1\"\x94\x02\n" +
	"\vCrawlRecord\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\vraw_content\x18\x02 \x01(\fR\n" +
	"rawContent\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.yase.ingestion.v1.CrawlRecord.MetadataEntryR\bmetadata\x12&\n" +
	"\x0fcrawled_at_unix\x18\x04 \x01(\x03R\rcrawledAtUnix\x12#\n" +
	"\rcollection_id\x18\x05 \x01(\tR\fcollectionId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x12BatchIngestRequest\x128\n" +
	"\arecords\x18\x01 \x03(\v2\x1e.yase.ingestion.v1.CrawlRecordR\arecords\"V\n" +
	"\x13BatchIngestResponse\x12'\n" +
	"\x0fprocessed_count\x18\x01 \x01(\x05R\x0eprocessedCount\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"M\n" +
	"\x13StreamIngestRequest\x126\n" +
	"\x06record\x18\x01 \x01(\v2\x1e.yase.ingestion.v1.CrawlRecordR\x06record\"@\n" +
	"\x14StreamIngestResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xd5\x01\n" +
	"\x10IngestionService\x12\\\n" +
	"\vIngestBatch\x12%.yase.ingestion.v1.BatchIngestRequest\x1a&.yase.ingestion.v1.BatchIngestResponse\x12c\n" +
	"\fIngestStream\x12&.yase.ingestion.v1.StreamIngestRequest\x1a'.yase.ingestion.v1.StreamIngestResponse(\x010\x01B.Z,github.com/efathom/yase/proto/v1;ingestionv1b\x06proto3"

var (
	file_proto_v1_ingestion_proto_rawDescOnce sync.Once
	file_proto_v1_ingestion_proto_rawDescData []byte
)

func file_proto_v1_ingestion_proto_rawDescGZIP() []byte {
	file_proto_v1_ingestion_proto_rawDescOnce.Do(func() {
		file_proto_v1_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_ingestion_proto_rawDesc), len(file_proto_v1_ingestion_proto_rawDesc)))
	})
	return file_proto_v1_ingestion_proto_rawDescData
}

var file_proto_v1_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_ingestion_proto_goTypes = []any{
	(*CrawlRecord)(nil),          // 0: yase.ingestion.v1.CrawlRecord
	(*BatchIngestRequest)(nil),   // 1: yase.ingestion.v1.BatchIngestRequest
	(*BatchIngestResponse)(nil),  // 2: yase.ingestion.v1.BatchIngestResponse
	(*StreamIngestRequest)(nil),  // 3: yase.ingestion.v1.StreamIngestRequest
	(*StreamIngestResponse)(nil), // 4: yase.ingestion.v1.StreamIngestResponse
	nil,                          // 5: yase.ingestion.v1.CrawlRecord.MetadataEntry
}
var file_proto_v1_ingestion_proto_depIdxs = []int32{
	5, // 0: yase.ingestion.v1.CrawlRecord.metadata:type_name -> yase.ingestion.v1.CrawlRecord.MetadataEntry
	0, // 1: yase.ingestion.v1.BatchIngestRequest.records:type_name -> yase.ingestion.v1.CrawlRecord
	0, // 2: yase.ingestion.v1.StreamIngestRequest.record:type_name -> yase.ingestion.v1.CrawlRecord
	1, // 3: yase.ingestion.v1.IngestionService.IngestBatch:input_type -> yase.ingestion.v1.BatchIngestRequest
	3, // 4: yase.ingestion.v1.IngestionService.IngestStream:input_type -> yase.ingestion.v1.StreamIngestRequest
	2, // 5: yase.ingestion.v1.IngestionService.IngestBatch:output_type -> yase.ingestion.v1.BatchIngestResponse
	4, // 6: yase.ingestion.v1.IngestionService.IngestStream:output_type -> yase.ingestion.v1.StreamIngestResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_ingestion_proto_init() }
func file_proto_v1_ingestion_proto_init() {
	if File_proto_v1_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_ingestion_proto_rawDesc), len(file_proto_v1_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_ingestion_proto_goTypes,
		DependencyIndexes: file_proto_v1_ingestion_proto_depIdxs,
		MessageInfos:      file_proto_v1_ingestion_proto_msgTypes,
	}.Build()
	File_proto_v1_ingestion_proto = out.File
	file_proto_v1_ingestion_proto_goTypes = nil
	file_proto_v1_ingestion_proto_depIdxs = nil
}
